travis:
  secure:
    BINSTAR_TOKEN: HRvgvBXCpIJ6SQh9xT4eneQNe95lvXooX+mG0QFpSVwAMeiqkUX7VGOI7AlLsxA/Tv+iCJqwom+OKKf8dfvc3pmWHstEwiPewA8R89Ci9TY0SU2+tHr8Im42IzHviTQhNm1FkUOxMBdO7elT2HNGOdJAdJKDLlZXlziI11F6kcfPkPlvqB0ecz1bxBEqDbsqRx1tP2xksifkAmTNMTZ5u89WsVuaaFQaCRNeW4VlIgUjVyMQh8w27Ze6pcvbd3clnXPEvuv4Ia3aF3L7r9dMx20topOOhP0W8A52g/XS1ynvdDtLSOZLnCkMsnDE0VjYIE6Z045xlML6XuAdNzXGD08eNiyOapimQq9m1GoSJcx+zPalLmFeVMKUl8eKg4sB5vOwz+lv9tx9YvilTfFTr4Z+nEQvf3a2f4rbbDpt34KMiPKWp8fDu+b3VLFZiy7ehBTGgrEBfABALVw01zieLs1S/biztXN4xihknKs2z8XHlgzMR0ugUWbaVr8iB9lXudb2xROEwtcXNklh8wO4awxgxyvrNBnkWkon+Fs3GY1WdMnn8Z4pLUpBmhpy9l/VVAXZLPLjqCTBnNLnwnDa0cvTrQAEwh/5Wop/3SbJWwtjLOLjGv70STKqk+lY+e6rJliVZtUSG8j/getySpdAiHCtZj28PmGiabePDXhXN5g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
