travis:
  secure:
    BINSTAR_TOKEN: Mcdwcvq8DjhB/0eqgLRkxYwvmkTymGMeDNpdWXSFI+99o6SWzgfqdkz1BmOLx1y6g5Y87IHGhoGeOhktmIA9LIl/Nl8S5fQYa50H4v1eLtbyjQIiZeMqec+MXoaYBc3ClsBayIHLP1cLmQEoSdOaZ3dwQUghwhmz5Gak2KfGgBg/KEhoTq+DsLuhxPZXiIbSVmwxi7Awwkpb1n5SmbIKxVfR0WgGD5JoAV90i/qW0ENWdtHPvXRe+hKz42TchoTTK3hJhRvYCvkjVIUeIXEY/H/WniAAcHjGq6qQUPQeOIl+DcuA5LmQ1garJLDx7SH8y5mQizMiLL9DB7gMGk+CZCABmW0Z9XUTRgbVdQ5RYuzynazr6UMDXSRex8ZDrAj8HBzXqaWgk8u+ObGoj9wP+emnBq3WNUEmdgjqfTS5Gh6uen6DIW7tNWOX9uF6FiuCge8UCfzq7e3UA0cDBCIYQr0fyalIB6CPM9Cc8jtAc5kNkbCKFn/BD5s2aVFa+DUUsa2ybjqhvbFa1XAnE0cHBx3wse0oKzDa5KhsV4szU5A+5xHXi4m+wLsM3rNmsKn625qqtSqRk9tRcJDqhlpba2/wNHYiI5gtrlfLjo2D+Hpqe4mi3FIFtHWk/s8kjP7KmXd8kG/g34MQ4cALl2yr/m+qKHBS8dK/ml9hfRtuj2k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
